#!/usr/bin/env python3
"""
WSI Embedding Analysis Pipeline for CPU-Only Systems (32GB RAM)

Comprehensive analysis pipeline for Whole Slide Image (WSI) embeddings using
UNI2 foundation model features. Designed for standard laptop without GPU.

Target Dataset: TCGA-CHOL (Cholangiocarcinoma)
- 90 tumor slides + 20 normal slides = 110 total
- 18.2% normal tissue (good for tumor vs normal classification)

Author: Generated by Claude
Date: 2025-02-05
"""

import os
import sys
import warnings
from pathlib import Path
from typing import Dict, List, Tuple, Optional, Any, Callable
from dataclasses import dataclass, field
import logging
import json
from datetime import datetime

import gc
import time

import numpy as np
import pandas as pd
import h5py
from scipy import stats
from scipy.stats import entropy as scipy_entropy
from scipy.cluster.hierarchy import linkage, fcluster, inconsistent
from scipy.spatial.distance import pdist

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans, AgglomerativeClustering
from sklearn.metrics import (
    silhouette_score, calinski_harabasz_score, roc_auc_score,
    f1_score, accuracy_score, precision_score, recall_score,
    confusion_matrix
)
from sklearn.model_selection import StratifiedKFold, LeaveOneOut, cross_val_predict

# Classification models
from sklearn.ensemble import (
    RandomForestClassifier, ExtraTreesClassifier, GradientBoostingClassifier,
    HistGradientBoostingClassifier, AdaBoostClassifier, BaggingClassifier
)
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression, RidgeClassifier, SGDClassifier
from sklearn.svm import LinearSVC, SVC, NuSVC
from sklearn.neighbors import KNeighborsClassifier, NearestCentroid
from sklearn.naive_bayes import GaussianNB, BernoulliNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

# Survival analysis
try:
    from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis, IPCRidge
    from sksurv.ensemble import (
        GradientBoostingSurvivalAnalysis, ComponentwiseGradientBoostingSurvivalAnalysis,
        RandomSurvivalForest, ExtraSurvivalTrees
    )
    from sksurv.svm import FastSurvivalSVM, FastKernelSurvivalSVM
    from sksurv.metrics import concordance_index_censored
    SKSURV_AVAILABLE = True
except ImportError:
    SKSURV_AVAILABLE = False
    warnings.warn("scikit-survival not installed. Survival models from sksurv will be unavailable.")

try:
    from lifelines import CoxPHFitter, WeibullAFTFitter, LogNormalAFTFitter, LogLogisticAFTFitter
    from lifelines.statistics import logrank_test
    LIFELINES_AVAILABLE = True
except ImportError:
    LIFELINES_AVAILABLE = False
    warnings.warn("lifelines not installed. Lifelines survival models will be unavailable.")

try:
    from xgboost import XGBClassifier
    XGBOOST_AVAILABLE = True
except ImportError:
    XGBOOST_AVAILABLE = False
    warnings.warn("xgboost not installed. XGBClassifier will be unavailable.")

try:
    from lightgbm import LGBMClassifier
    LIGHTGBM_AVAILABLE = True
except ImportError:
    LIGHTGBM_AVAILABLE = False
    warnings.warn("lightgbm not installed. LGBMClassifier will be unavailable.")

try:
    from catboost import CatBoostClassifier
    CATBOOST_AVAILABLE = True
except ImportError:
    CATBOOST_AVAILABLE = False
    warnings.warn("catboost not installed. CatBoostClassifier will be unavailable.")

from statsmodels.stats.multitest import multipletests

import matplotlib
matplotlib.use('Agg')  # Non-interactive backend for server/headless use
import matplotlib.pyplot as plt
import seaborn as sns

# Suppress warnings for cleaner output
warnings.filterwarnings('ignore', category=FutureWarning)
warnings.filterwarnings('ignore', category=UserWarning)

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.StreamHandler(sys.stdout)
    ]
)
logger = logging.getLogger(__name__)


# =============================================================================
# 1. CONFIGURATION & PATHS
# =============================================================================

@dataclass
class Config:
    """Configuration for the WSI embedding analysis pipeline."""

    # Input paths
    embeddings_dir: Path = Path(r"C:\Users\Jia Yin\Desktop\Mentorship\JiaYin_WSI_Analysis\embeddings")
    clinical_data_path: Path = Path(r"C:\Users\Jia Yin\Desktop\Mentorship\JiaYin_WSI_Analysis\CLINICAL_FULL.parquet")

    # Output paths
    output_dir: Path = Path(r"C:\Users\Jia Yin\Desktop\Mentorship\JiaYin_WSI_Analysis\results")

    # Analysis parameters
    cancer_type: str = "CHOL"
    embedding_dim: int = 1536  # UNI2 embedding dimension
    pca_variance_threshold: float = 0.95  # 95% variance retained
    max_clusters: int = 10
    min_clusters: int = 2

    # Cross-validation
    n_folds: int = 5
    random_state: int = 42

    # FDR correction
    fdr_alpha: float = 0.05

    # Memory management
    max_slides_in_memory: int = 20
    cooldown_seconds: float = 0.5  # Pause between files to reduce thermal load

    def __post_init__(self):
        """Create output directories."""
        self.output_dir.mkdir(parents=True, exist_ok=True)
        (self.output_dir / "aggregated_embeddings").mkdir(exist_ok=True)
        (self.output_dir / "pca_results").mkdir(exist_ok=True)
        (self.output_dir / "clustering_results").mkdir(exist_ok=True)
        (self.output_dir / "survival_results").mkdir(exist_ok=True)
        (self.output_dir / "classification_results").mkdir(exist_ok=True)
        (self.output_dir / "statistical_tests").mkdir(exist_ok=True)
        (self.output_dir / "figures").mkdir(exist_ok=True)


# =============================================================================
# 2. AGGREGATION FUNCTIONS (43 METHODS)
# =============================================================================

class AggregationMethods:
    """Collection of 43 aggregation methods for patch embeddings."""

    @staticmethod
    def mean(embeddings: np.ndarray) -> np.ndarray:
        """Simple arithmetic mean."""
        return np.mean(embeddings, axis=0)

    @staticmethod
    def median(embeddings: np.ndarray) -> np.ndarray:
        """Median along patches."""
        return np.median(embeddings, axis=0)

    @staticmethod
    def trimmed_mean(embeddings: np.ndarray, proportion: float = 0.1) -> np.ndarray:
        """Trimmed mean excluding top/bottom 10%."""
        return stats.trim_mean(embeddings, proportion, axis=0)

    @staticmethod
    def winsorized_mean(embeddings: np.ndarray, limits: Tuple[float, float] = (0.1, 0.1)) -> np.ndarray:
        """Winsorized mean (cap extremes instead of remove)."""
        from scipy.stats import mstats
        return np.mean(mstats.winsorize(embeddings, limits=limits, axis=0), axis=0)

    @staticmethod
    def geometric_mean(embeddings: np.ndarray) -> np.ndarray:
        """Geometric mean (after shifting to positive values)."""
        # Shift to positive domain
        shifted = embeddings - embeddings.min(axis=0) + 1e-10
        return stats.gmean(shifted, axis=0) + embeddings.min(axis=0) - 1e-10

    @staticmethod
    def harmonic_mean(embeddings: np.ndarray) -> np.ndarray:
        """Harmonic mean (after shifting to positive values)."""
        shifted = embeddings - embeddings.min(axis=0) + 1e-10
        return stats.hmean(shifted, axis=0) + embeddings.min(axis=0) - 1e-10

    @staticmethod
    def std(embeddings: np.ndarray) -> np.ndarray:
        """Standard deviation."""
        return np.std(embeddings, axis=0)

    @staticmethod
    def var(embeddings: np.ndarray) -> np.ndarray:
        """Variance."""
        return np.var(embeddings, axis=0)

    @staticmethod
    def range_agg(embeddings: np.ndarray) -> np.ndarray:
        """Range (max - min)."""
        return np.ptp(embeddings, axis=0)

    @staticmethod
    def cv(embeddings: np.ndarray) -> np.ndarray:
        """Coefficient of variation (std/mean)."""
        mean_vals = np.mean(embeddings, axis=0)
        std_vals = np.std(embeddings, axis=0)
        # Avoid division by zero
        return np.divide(std_vals, mean_vals, out=np.zeros_like(std_vals), where=mean_vals != 0)

    @staticmethod
    def iqr(embeddings: np.ndarray) -> np.ndarray:
        """Interquartile range."""
        return stats.iqr(embeddings, axis=0)

    @staticmethod
    def mad(embeddings: np.ndarray) -> np.ndarray:
        """Median absolute deviation."""
        return stats.median_abs_deviation(embeddings, axis=0)

    @staticmethod
    def mid_range(embeddings: np.ndarray) -> np.ndarray:
        """Mid-range ((max + min) / 2)."""
        return (np.max(embeddings, axis=0) + np.min(embeddings, axis=0)) / 2

    @staticmethod
    def entropy_agg(embeddings: np.ndarray, bins: int = 50) -> np.ndarray:
        """Shannon entropy of discretized values per dimension."""
        result = np.zeros(embeddings.shape[1])
        for i in range(embeddings.shape[1]):
            hist, _ = np.histogram(embeddings[:, i], bins=bins, density=True)
            hist = hist + 1e-10  # Avoid log(0)
            result[i] = scipy_entropy(hist)
        return result

    @staticmethod
    def skewness(embeddings: np.ndarray) -> np.ndarray:
        """Skewness of distribution."""
        return stats.skew(embeddings, axis=0)

    @staticmethod
    def kurtosis(embeddings: np.ndarray) -> np.ndarray:
        """Kurtosis of distribution."""
        return stats.kurtosis(embeddings, axis=0)

    @staticmethod
    def percentile_5(embeddings: np.ndarray) -> np.ndarray:
        """5th percentile."""
        return np.percentile(embeddings, 5, axis=0)

    @staticmethod
    def percentile_10(embeddings: np.ndarray) -> np.ndarray:
        """10th percentile."""
        return np.percentile(embeddings, 10, axis=0)

    @staticmethod
    def percentile_25(embeddings: np.ndarray) -> np.ndarray:
        """25th percentile (Q1)."""
        return np.percentile(embeddings, 25, axis=0)

    @staticmethod
    def percentile_50(embeddings: np.ndarray) -> np.ndarray:
        """50th percentile (median)."""
        return np.percentile(embeddings, 50, axis=0)

    @staticmethod
    def percentile_75(embeddings: np.ndarray) -> np.ndarray:
        """75th percentile (Q3)."""
        return np.percentile(embeddings, 75, axis=0)

    @staticmethod
    def percentile_90(embeddings: np.ndarray) -> np.ndarray:
        """90th percentile."""
        return np.percentile(embeddings, 90, axis=0)

    @staticmethod
    def percentile_95(embeddings: np.ndarray) -> np.ndarray:
        """95th percentile."""
        return np.percentile(embeddings, 95, axis=0)

    @staticmethod
    def max_agg(embeddings: np.ndarray) -> np.ndarray:
        """Maximum value."""
        return np.max(embeddings, axis=0)

    @staticmethod
    def min_agg(embeddings: np.ndarray) -> np.ndarray:
        """Minimum value."""
        return np.min(embeddings, axis=0)

    @staticmethod
    def top5_mean(embeddings: np.ndarray) -> np.ndarray:
        """Mean of top 5% patches by L2 norm."""
        norms = np.linalg.norm(embeddings, axis=1)
        k = max(1, int(len(embeddings) * 0.05))
        top_indices = np.argsort(norms)[-k:]
        return np.mean(embeddings[top_indices], axis=0)

    @staticmethod
    def top10_mean(embeddings: np.ndarray) -> np.ndarray:
        """Mean of top 10% patches by L2 norm."""
        norms = np.linalg.norm(embeddings, axis=1)
        k = max(1, int(len(embeddings) * 0.10))
        top_indices = np.argsort(norms)[-k:]
        return np.mean(embeddings[top_indices], axis=0)

    @staticmethod
    def bottom5_mean(embeddings: np.ndarray) -> np.ndarray:
        """Mean of bottom 5% patches by L2 norm."""
        norms = np.linalg.norm(embeddings, axis=1)
        k = max(1, int(len(embeddings) * 0.05))
        bottom_indices = np.argsort(norms)[:k]
        return np.mean(embeddings[bottom_indices], axis=0)

    @staticmethod
    def bottom10_mean(embeddings: np.ndarray) -> np.ndarray:
        """Mean of bottom 10% patches by L2 norm."""
        norms = np.linalg.norm(embeddings, axis=1)
        k = max(1, int(len(embeddings) * 0.10))
        bottom_indices = np.argsort(norms)[:k]
        return np.mean(embeddings[bottom_indices], axis=0)

    @staticmethod
    def top5_mean_L1(embeddings: np.ndarray) -> np.ndarray:
        """Mean of top 5% patches by L1 norm."""
        norms = np.linalg.norm(embeddings, ord=1, axis=1)
        k = max(1, int(len(embeddings) * 0.05))
        top_indices = np.argsort(norms)[-k:]
        return np.mean(embeddings[top_indices], axis=0)

    @staticmethod
    def median_patch(embeddings: np.ndarray) -> np.ndarray:
        """Single patch closest to median embedding."""
        median_emb = np.median(embeddings, axis=0)
        distances = np.linalg.norm(embeddings - median_emb, axis=1)
        return embeddings[np.argmin(distances)]

    @staticmethod
    def entropy_weighted_mean(embeddings: np.ndarray, bins: int = 50) -> np.ndarray:
        """Mean weighted by inverse entropy (higher weight to consistent patches)."""
        # Compute entropy per patch
        patch_entropies = np.zeros(len(embeddings))
        for i, patch in enumerate(embeddings):
            hist, _ = np.histogram(patch, bins=bins, density=True)
            hist = hist + 1e-10
            patch_entropies[i] = scipy_entropy(hist)

        # Inverse entropy as weight (low entropy = high weight)
        weights = 1.0 / (patch_entropies + 1e-10)
        weights = weights / weights.sum()
        return np.average(embeddings, axis=0, weights=weights)

    @staticmethod
    def variance_weighted_mean(embeddings: np.ndarray) -> np.ndarray:
        """Mean weighted by inverse variance (higher weight to consistent patches)."""
        patch_vars = np.var(embeddings, axis=1)
        weights = 1.0 / (patch_vars + 1e-10)
        weights = weights / weights.sum()
        return np.average(embeddings, axis=0, weights=weights)

    @staticmethod
    def rms(embeddings: np.ndarray) -> np.ndarray:
        """Root mean square."""
        return np.sqrt(np.mean(embeddings ** 2, axis=0))

    @staticmethod
    def sum_abs(embeddings: np.ndarray) -> np.ndarray:
        """Sum of absolute values per dimension."""
        return np.sum(np.abs(embeddings), axis=0)

    # Mega-vectors (concatenations)
    @staticmethod
    def mega_mean_minmax(embeddings: np.ndarray) -> np.ndarray:
        """Mega-vector: mean + min + max (4,608 dims)."""
        return np.concatenate([
            AggregationMethods.mean(embeddings),
            AggregationMethods.min_agg(embeddings),
            AggregationMethods.max_agg(embeddings)
        ])

    @staticmethod
    def mega_mean_extremes(embeddings: np.ndarray) -> np.ndarray:
        """Mega-vector: mean + top5 + bottom5 + top10 + bottom10 (7,680 dims)."""
        return np.concatenate([
            AggregationMethods.mean(embeddings),
            AggregationMethods.top5_mean(embeddings),
            AggregationMethods.bottom5_mean(embeddings),
            AggregationMethods.top10_mean(embeddings),
            AggregationMethods.bottom10_mean(embeddings)
        ])

    @staticmethod
    def mega_mean_percentiles(embeddings: np.ndarray) -> np.ndarray:
        """Mega-vector: mean + P10 + P25 + P75 + P90 (7,680 dims)."""
        return np.concatenate([
            AggregationMethods.mean(embeddings),
            AggregationMethods.percentile_10(embeddings),
            AggregationMethods.percentile_25(embeddings),
            AggregationMethods.percentile_75(embeddings),
            AggregationMethods.percentile_90(embeddings)
        ])

    @staticmethod
    def mega_central_spread(embeddings: np.ndarray) -> np.ndarray:
        """Mega-vector: mean + std + var + range + iqr (7,680 dims)."""
        return np.concatenate([
            AggregationMethods.mean(embeddings),
            AggregationMethods.std(embeddings),
            AggregationMethods.var(embeddings),
            AggregationMethods.range_agg(embeddings),
            AggregationMethods.iqr(embeddings)
        ])

    @staticmethod
    def mega_robust(embeddings: np.ndarray) -> np.ndarray:
        """Mega-vector: median + trimmed_mean + iqr + P25 + P75 (7,680 dims)."""
        return np.concatenate([
            AggregationMethods.median(embeddings),
            AggregationMethods.trimmed_mean(embeddings),
            AggregationMethods.iqr(embeddings),
            AggregationMethods.percentile_25(embeddings),
            AggregationMethods.percentile_75(embeddings)
        ])

    @staticmethod
    def mega_full(embeddings: np.ndarray) -> np.ndarray:
        """Mega-vector: mean + min + max + top5 + bottom5 + std + range (10,752 dims)."""
        return np.concatenate([
            AggregationMethods.mean(embeddings),
            AggregationMethods.min_agg(embeddings),
            AggregationMethods.max_agg(embeddings),
            AggregationMethods.top5_mean(embeddings),
            AggregationMethods.bottom5_mean(embeddings),
            AggregationMethods.std(embeddings),
            AggregationMethods.range_agg(embeddings)
        ])

    @staticmethod
    def mega_distribution(embeddings: np.ndarray) -> np.ndarray:
        """Mega-vector: mean + std + skewness + kurtosis (6,144 dims)."""
        return np.concatenate([
            AggregationMethods.mean(embeddings),
            AggregationMethods.std(embeddings),
            AggregationMethods.skewness(embeddings),
            AggregationMethods.kurtosis(embeddings)
        ])

    @staticmethod
    def mega_all_percentiles(embeddings: np.ndarray) -> np.ndarray:
        """Mega-vector: P5 + P10 + P25 + P50 + P75 + P90 + P95 (10,752 dims)."""
        return np.concatenate([
            AggregationMethods.percentile_5(embeddings),
            AggregationMethods.percentile_10(embeddings),
            AggregationMethods.percentile_25(embeddings),
            AggregationMethods.percentile_50(embeddings),
            AggregationMethods.percentile_75(embeddings),
            AggregationMethods.percentile_90(embeddings),
            AggregationMethods.percentile_95(embeddings)
        ])


def get_all_aggregation_methods() -> Dict[str, Callable]:
    """Return dictionary of all 43 aggregation methods."""
    return {
        # Central Tendency (6)
        'mean': AggregationMethods.mean,
        'median': AggregationMethods.median,
        'trimmed_mean': AggregationMethods.trimmed_mean,
        'winsorized_mean': AggregationMethods.winsorized_mean,
        'geometric_mean': AggregationMethods.geometric_mean,
        'harmonic_mean': AggregationMethods.harmonic_mean,

        # Dispersion/Spread (7)
        'std': AggregationMethods.std,
        'var': AggregationMethods.var,
        'range': AggregationMethods.range_agg,
        'cv': AggregationMethods.cv,
        'iqr': AggregationMethods.iqr,
        'mad': AggregationMethods.mad,
        'mid_range': AggregationMethods.mid_range,

        # Distribution Shape (3)
        'entropy': AggregationMethods.entropy_agg,
        'skewness': AggregationMethods.skewness,
        'kurtosis': AggregationMethods.kurtosis,

        # Percentiles (7)
        'percentile_5': AggregationMethods.percentile_5,
        'percentile_10': AggregationMethods.percentile_10,
        'percentile_25': AggregationMethods.percentile_25,
        'percentile_50': AggregationMethods.percentile_50,
        'percentile_75': AggregationMethods.percentile_75,
        'percentile_90': AggregationMethods.percentile_90,
        'percentile_95': AggregationMethods.percentile_95,

        # Extreme Value / Top-K (8)
        'max': AggregationMethods.max_agg,
        'min': AggregationMethods.min_agg,
        'top5_mean': AggregationMethods.top5_mean,
        'top10_mean': AggregationMethods.top10_mean,
        'bottom5_mean': AggregationMethods.bottom5_mean,
        'bottom10_mean': AggregationMethods.bottom10_mean,
        'top5_mean_L1': AggregationMethods.top5_mean_L1,
        'median_patch': AggregationMethods.median_patch,

        # Weighted Aggregations (2)
        'entropy_weighted_mean': AggregationMethods.entropy_weighted_mean,
        'variance_weighted_mean': AggregationMethods.variance_weighted_mean,

        # Energy/Magnitude (2)
        'rms': AggregationMethods.rms,
        'sum_abs': AggregationMethods.sum_abs,

        # Mega-Vectors (8)
        'mega_mean_minmax': AggregationMethods.mega_mean_minmax,
        'mega_mean_extremes': AggregationMethods.mega_mean_extremes,
        'mega_mean_percentiles': AggregationMethods.mega_mean_percentiles,
        'mega_central_spread': AggregationMethods.mega_central_spread,
        'mega_robust': AggregationMethods.mega_robust,
        'mega_full': AggregationMethods.mega_full,
        'mega_distribution': AggregationMethods.mega_distribution,
        'mega_all_percentiles': AggregationMethods.mega_all_percentiles,
    }


# =============================================================================
# 3. DATA LOADING UTILITIES
# =============================================================================

class DataLoader:
    """Utility class for loading embeddings and clinical data."""

    def __init__(self, config: Config):
        self.config = config
        self.clinical_data = None
        self.slide_metadata = None

    def load_clinical_data(self) -> pd.DataFrame:
        """Load and filter clinical data for the specified cancer type."""
        logger.info(f"Loading clinical data from {self.config.clinical_data_path}")

        if not self.config.clinical_data_path.exists():
            raise FileNotFoundError(f"Clinical data not found: {self.config.clinical_data_path}")

        clinical = pd.read_parquet(self.config.clinical_data_path)

        # If participant_id is the index, make it a column
        if clinical.index.name == 'participant_id':
            clinical = clinical.reset_index()

        # Filter for cancer type
        if 'project_id' in clinical.columns:
            clinical = clinical[clinical['project_id'] == f"TCGA-{self.config.cancer_type}"]
        elif 'cancer_type' in clinical.columns:
            clinical = clinical[clinical['cancer_type'] == self.config.cancer_type]

        logger.info(f"Loaded {len(clinical)} samples for TCGA-{self.config.cancer_type}")

        self.clinical_data = clinical
        return clinical

    def load_slide_embeddings(self, slide_path: Path) -> np.ndarray:
        """Load embeddings from a single H5 file using memory-mapped reads.

        Opens the file with driver='core' and backing_store=False to avoid
        keeping the entire dataset resident.  For very large datasets the
        arrays are read in chunks so the OS can page memory efficiently.
        """
        with h5py.File(slide_path, 'r', rdcc_nbytes=0) as f:
            # Common key names for embeddings
            dataset = None
            for key in ['features', 'embeddings', 'feats', 'data']:
                if key in f:
                    dataset = f[key]
                    break
            if dataset is None:
                for key in f.keys():
                    if isinstance(f[key], h5py.Dataset):
                        dataset = f[key]
                        break

            if dataset is None:
                raise ValueError(f"Could not find embeddings in {slide_path}")

            shape = dataset.shape
            dtype = dataset.dtype

            # Read in chunks to limit peak memory (64 MB per chunk)
            chunk_bytes = 64 * 1024 * 1024
            row_bytes = int(np.prod(shape[1:])) * np.dtype(dtype).itemsize if len(shape) > 1 else np.dtype(dtype).itemsize
            rows_per_chunk = max(1, chunk_bytes // max(row_bytes, 1))

            arr = np.empty(shape, dtype=np.float32)
            for start in range(0, shape[0], rows_per_chunk):
                end = min(start + rows_per_chunk, shape[0])
                arr[start:end] = dataset[start:end]

            # UNI2 format: (1, N, 1536) -> squeeze to (N, 1536)
            if arr.ndim == 3 and arr.shape[0] == 1:
                arr = arr.squeeze(0)
            return arr

    def discover_slides(self) -> List[Dict[str, Any]]:
        """Discover all available slide embeddings and match with clinical data."""
        logger.info(f"Discovering slides in {self.config.embeddings_dir}")

        slides = []
        h5_files = list(self.config.embeddings_dir.glob("**/*.h5"))
        h5_files.extend(list(self.config.embeddings_dir.glob("**/*.hdf5")))

        logger.info(f"Found {len(h5_files)} H5 files")

        for h5_path in h5_files:
            # Extract TCGA barcode from filename
            filename = h5_path.stem

            # Try to parse TCGA barcode (e.g., TCGA-W5-AA2R-01A-01-TS1)
            parts = filename.split('-')
            if len(parts) >= 4 and parts[0] == 'TCGA':
                participant_id = '-'.join(parts[:3])
                sample_type_code = parts[3][:2] if len(parts) > 3 else '01'

                # Determine if tumor or normal based on sample type code
                # 01-09 = tumor, 10-19 = normal (11 = solid tissue normal)
                try:
                    code = int(sample_type_code)
                    is_tumor = code < 10
                except ValueError:
                    is_tumor = True  # Default to tumor if can't parse

                slides.append({
                    'path': h5_path,
                    'filename': filename,
                    'participant_id': participant_id,
                    'sample_type_code': sample_type_code,
                    'is_tumor': is_tumor,
                    'label': 'tumor' if is_tumor else 'normal'
                })

        self.slide_metadata = pd.DataFrame(slides)
        logger.info(f"Discovered {len(slides)} slides")

        if len(slides) > 0:
            tumor_count = sum(1 for s in slides if s['is_tumor'])
            normal_count = len(slides) - tumor_count
            logger.info(f"  Tumor: {tumor_count}, Normal: {normal_count}")

        return slides

    def get_survival_data(self) -> pd.DataFrame:
        """Extract survival data from clinical data."""
        if self.clinical_data is None:
            self.load_clinical_data()

        clinical = self.clinical_data.copy()

        # Create survival outcome
        # Check for various column naming conventions
        time_cols = ['days_to_death', 'days_to_last_followup', 'days_to_last_follow_up',
                     'overall_survival', 'OS.time']
        status_cols = ['vital_status', 'OS', 'deceased']

        time_col = None
        status_col = None

        for col in time_cols:
            if col in clinical.columns:
                time_col = col
                break

        for col in status_cols:
            if col in clinical.columns:
                status_col = col
                break

        if time_col is None or status_col is None:
            logger.warning("Could not find survival columns in clinical data")
            return pd.DataFrame()

        # Create combined time column
        if 'days_to_death' in clinical.columns and 'days_to_last_followup' in clinical.columns:
            clinical['time'] = clinical['days_to_death'].fillna(clinical['days_to_last_followup'])
        else:
            clinical['time'] = clinical[time_col]

        # Create event indicator (1 = death, 0 = censored)
        if status_col == 'vital_status':
            clinical['event'] = (clinical[status_col].str.lower() == 'dead').astype(int)
        else:
            clinical['event'] = clinical[status_col].astype(int)

        # Remove samples with missing survival data
        survival_data = clinical[['participant_id', 'time', 'event']].dropna()
        survival_data = survival_data[survival_data['time'] > 0]

        logger.info(f"Survival data: {len(survival_data)} samples, {survival_data['event'].sum()} events")

        return survival_data


# =============================================================================
# 4. PCA & CLUSTERING PIPELINE
# =============================================================================

class ClusteringPipeline:
    """PCA and clustering analysis pipeline."""

    def __init__(self, config: Config):
        self.config = config
        self.pca_models = {}
        self.cluster_results = {}

    def fit_pca(self, embeddings: np.ndarray, method_name: str) -> Tuple[np.ndarray, PCA]:
        """Fit PCA with 95% variance threshold."""
        logger.info(f"Fitting PCA for {method_name} (input dim: {embeddings.shape[1]})")

        # Standardize
        scaler = StandardScaler()
        embeddings_scaled = scaler.fit_transform(embeddings)

        # Fit PCA with variance threshold
        pca = PCA(n_components=self.config.pca_variance_threshold, svd_solver='full')
        embeddings_pca = pca.fit_transform(embeddings_scaled)

        logger.info(f"  PCA reduced to {pca.n_components_} components "
                   f"({pca.explained_variance_ratio_.sum():.2%} variance)")

        self.pca_models[method_name] = {
            'pca': pca,
            'scaler': scaler,
            'n_components': pca.n_components_,
            'explained_variance': pca.explained_variance_ratio_.sum()
        }

        return embeddings_pca, pca

    def find_optimal_k(self, embeddings: np.ndarray, method: str = 'silhouette') -> int:
        """Find optimal number of clusters using silhouette score."""
        best_k = 2
        best_score = -1

        scores = {}
        for k in range(self.config.min_clusters, min(self.config.max_clusters + 1, len(embeddings))):
            kmeans = KMeans(n_clusters=k, random_state=self.config.random_state, n_init=10)
            labels = kmeans.fit_predict(embeddings)

            if method == 'silhouette':
                score = silhouette_score(embeddings, labels)
            elif method == 'calinski':
                score = calinski_harabasz_score(embeddings, labels)
            else:
                score = silhouette_score(embeddings, labels)

            scores[k] = score
            if score > best_score:
                best_score = score
                best_k = k

        return best_k, scores

    def cluster_kmeans(self, embeddings: np.ndarray, k: int) -> np.ndarray:
        """Perform K-means clustering."""
        kmeans = KMeans(n_clusters=k, random_state=self.config.random_state, n_init=10)
        return kmeans.fit_predict(embeddings)

    def cluster_hierarchical(self, embeddings: np.ndarray, k: int) -> np.ndarray:
        """Perform hierarchical (Ward) clustering."""
        clustering = AgglomerativeClustering(n_clusters=k, linkage='ward')
        return clustering.fit_predict(embeddings)

    def run_clustering_analysis(self, embeddings: np.ndarray, method_name: str,
                                labels: np.ndarray, survival_data: Optional[pd.DataFrame] = None,
                                slide_participant_ids: Optional[List[str]] = None) -> Dict:
        """Run full clustering analysis for one aggregation method."""
        results = {
            'method_name': method_name,
            'n_samples': len(embeddings)
        }

        # PCA
        embeddings_pca, pca = self.fit_pca(embeddings, method_name)
        results['pca_n_components'] = pca.n_components_
        results['pca_variance_explained'] = pca.explained_variance_ratio_.sum()

        # Find optimal k
        optimal_k, silhouette_scores = self.find_optimal_k(embeddings_pca)
        results['optimal_k'] = optimal_k
        results['silhouette_scores'] = silhouette_scores

        # K-means clustering
        kmeans_labels = self.cluster_kmeans(embeddings_pca, optimal_k)
        results['kmeans_labels'] = kmeans_labels
        results['kmeans_silhouette'] = silhouette_score(embeddings_pca, kmeans_labels)

        # Hierarchical clustering
        hier_labels = self.cluster_hierarchical(embeddings_pca, optimal_k)
        results['hierarchical_labels'] = hier_labels
        results['hierarchical_silhouette'] = silhouette_score(embeddings_pca, hier_labels)

        # Statistical tests
        # Chi-square: clusters vs tumor/normal
        if labels is not None and len(np.unique(labels)) > 1:
            for cluster_type, cluster_labels in [('kmeans', kmeans_labels), ('hierarchical', hier_labels)]:
                contingency = pd.crosstab(cluster_labels, labels)
                chi2, pval, dof, expected = stats.chi2_contingency(contingency)
                results[f'{cluster_type}_chi2_stat'] = chi2
                results[f'{cluster_type}_chi2_pval'] = pval

        # Log-rank test: clusters vs survival
        # Align cluster labels with survival data via participant_id
        if (survival_data is not None and len(survival_data) > 0
                and LIFELINES_AVAILABLE and slide_participant_ids is not None):
            # Build mapping: participant_id -> cluster label
            surv_pids = set(survival_data['participant_id'].values)
            surv_indices = []
            cluster_indices = []
            for i, pid in enumerate(slide_participant_ids):
                if pid in surv_pids:
                    surv_indices.append(pid)
                    cluster_indices.append(i)

            if len(cluster_indices) >= 4:  # Need at least a few samples per cluster
                surv_subset = survival_data[survival_data['participant_id'].isin(surv_indices)].copy()
                # Map participant_id to cluster label
                pid_to_idx = {pid: i for i, pid in enumerate(slide_participant_ids)}

                for cluster_type, all_cluster_labels in [('kmeans', kmeans_labels), ('hierarchical', hier_labels)]:
                    try:
                        # Get cluster labels aligned with survival data
                        aligned_labels = np.array([
                            all_cluster_labels[pid_to_idx[pid]]
                            for pid in surv_subset['participant_id'].values
                        ])
                        unique_clusters = np.unique(aligned_labels)
                        if len(unique_clusters) >= 2:
                            mask1 = aligned_labels == unique_clusters[0]
                            mask2 = aligned_labels == unique_clusters[1]

                            lr_result = logrank_test(
                                surv_subset.loc[surv_subset.index[mask1], 'time'].values,
                                surv_subset.loc[surv_subset.index[mask2], 'time'].values,
                                surv_subset.loc[surv_subset.index[mask1], 'event'].values,
                                surv_subset.loc[surv_subset.index[mask2], 'event'].values
                            )
                            results[f'{cluster_type}_logrank_stat'] = lr_result.test_statistic
                            results[f'{cluster_type}_logrank_pval'] = lr_result.p_value
                    except Exception as e:
                        logger.warning(f"Log-rank test failed for {method_name} {cluster_type}: {e}")

        self.cluster_results[method_name] = results
        return results


# =============================================================================
# 5. SURVIVAL MODEL DEFINITIONS (16 MODELS)
# =============================================================================

def get_survival_models(random_state: int = 42) -> Dict[str, Any]:
    """Return dictionary of all 16 survival models."""
    models = {}

    if SKSURV_AVAILABLE:
        # Cox-Based (scikit-survival)
        models['CoxPH'] = CoxPHSurvivalAnalysis()
        models['CoxnetLasso'] = CoxnetSurvivalAnalysis(l1_ratio=1.0, alpha_min_ratio=0.01)
        models['CoxnetRidge'] = CoxnetSurvivalAnalysis(l1_ratio=0.01, alpha_min_ratio=0.01)  # Near-zero for ridge-like
        models['CoxnetElasticNet'] = CoxnetSurvivalAnalysis(l1_ratio=0.5, alpha_min_ratio=0.01)

        # Tree-Based (scikit-survival)
        models['GradientBoostingSurvival'] = GradientBoostingSurvivalAnalysis(
            n_estimators=100, max_depth=3, random_state=random_state
        )
        models['ComponentwiseGradientBoosting'] = ComponentwiseGradientBoostingSurvivalAnalysis(
            n_estimators=100, random_state=random_state
        )
        models['RandomSurvivalForest'] = RandomSurvivalForest(
            n_estimators=100, max_depth=5, random_state=random_state, n_jobs=-1
        )
        models['ExtraSurvivalTrees'] = ExtraSurvivalTrees(
            n_estimators=100, max_depth=5, random_state=random_state, n_jobs=-1
        )

        # SVM-Based (scikit-survival)
        models['FastSurvivalSVM'] = FastSurvivalSVM(random_state=random_state)
        # FastKernelSurvivalSVM flagged as slower
        models['FastKernelSurvivalSVM'] = FastKernelSurvivalSVM(
            kernel='rbf', random_state=random_state
        )

        # Other (scikit-survival)
        models['IPCRidge'] = IPCRidge()

    if LIFELINES_AVAILABLE:
        # Accelerated Failure Time (lifelines)
        # These need special handling as they work differently
        models['WeibullAFT'] = 'lifelines_weibull'
        models['LogNormalAFT'] = 'lifelines_lognormal'
        models['LogLogisticAFT'] = 'lifelines_loglogistic'
        models['CoxPHFitter'] = 'lifelines_cox'

    return models


# =============================================================================
# 6. CLASSIFICATION MODEL DEFINITIONS (24 MODELS)
# =============================================================================

def get_classification_models(random_state: int = 42) -> Dict[str, Any]:
    """Return dictionary of all 24 classification models."""
    models = {}

    # Tree-Based Ensembles (10)
    models['RandomForest'] = RandomForestClassifier(
        n_estimators=100, max_depth=10, random_state=random_state, n_jobs=-1
    )
    models['ExtraTrees'] = ExtraTreesClassifier(
        n_estimators=100, max_depth=10, random_state=random_state, n_jobs=-1
    )
    models['GradientBoosting'] = GradientBoostingClassifier(
        n_estimators=100, max_depth=3, random_state=random_state
    )
    models['HistGradientBoosting'] = HistGradientBoostingClassifier(
        max_iter=100, max_depth=5, random_state=random_state
    )
    models['AdaBoost'] = AdaBoostClassifier(
        n_estimators=50, random_state=random_state
    )
    models['Bagging'] = BaggingClassifier(
        n_estimators=50, random_state=random_state, n_jobs=-1
    )
    models['DecisionTree'] = DecisionTreeClassifier(
        max_depth=10, random_state=random_state
    )

    if XGBOOST_AVAILABLE:
        models['XGBoost'] = XGBClassifier(
            n_estimators=100, max_depth=5, random_state=random_state,
            use_label_encoder=False, eval_metric='logloss', verbosity=0
        )

    if LIGHTGBM_AVAILABLE:
        models['LightGBM'] = LGBMClassifier(
            n_estimators=100, max_depth=5, random_state=random_state, verbose=-1
        )

    if CATBOOST_AVAILABLE:
        models['CatBoost'] = CatBoostClassifier(
            iterations=100, depth=5, random_state=random_state, verbose=False
        )

    # Linear Models (5)
    models['LogisticRegression_L2'] = LogisticRegression(
        penalty='l2', solver='lbfgs', max_iter=1000, random_state=random_state
    )
    models['LogisticRegression_L1'] = LogisticRegression(
        penalty='l1', solver='saga', max_iter=1000, random_state=random_state
    )
    models['LogisticRegression_ElasticNet'] = LogisticRegression(
        penalty='elasticnet', solver='saga', l1_ratio=0.5, max_iter=1000, random_state=random_state
    )
    models['RidgeClassifier'] = RidgeClassifier(random_state=random_state)
    models['SGDClassifier'] = SGDClassifier(
        loss='log_loss', penalty='l2', max_iter=1000, random_state=random_state
    )

    # SVM (4)
    models['LinearSVC'] = LinearSVC(max_iter=10000, random_state=random_state)
    models['SVC_linear'] = SVC(kernel='linear', probability=True, random_state=random_state)
    # Flagged as slow for larger datasets
    models['SVC_rbf'] = SVC(kernel='rbf', probability=True, random_state=random_state)
    models['NuSVC'] = NuSVC(probability=True, random_state=random_state)

    # Neighbors (2)
    models['KNeighbors'] = KNeighborsClassifier(n_neighbors=5, n_jobs=-1)
    models['NearestCentroid'] = NearestCentroid()

    # Naive Bayes (2)
    models['GaussianNB'] = GaussianNB()
    models['BernoulliNB'] = BernoulliNB()

    # Discriminant Analysis (1)
    models['LDA'] = LinearDiscriminantAnalysis()

    return models


# =============================================================================
# 7. CROSS-VALIDATION FUNCTIONS
# =============================================================================

class CrossValidation:
    """Cross-validation utilities for survival and classification."""

    def __init__(self, config: Config):
        self.config = config

    def stratified_kfold_classification(self, X: np.ndarray, y: np.ndarray,
                                        model: Any, model_name: str) -> Dict:
        """Run stratified 5-fold CV for classification."""
        skf = StratifiedKFold(n_splits=self.config.n_folds, shuffle=True,
                             random_state=self.config.random_state)

        metrics = {
            'auc': [], 'f1': [], 'accuracy': [],
            'precision': [], 'recall': []
        }

        for fold, (train_idx, test_idx) in enumerate(skf.split(X, y)):
            X_train, X_test = X[train_idx], X[test_idx]
            y_train, y_test = y[train_idx], y[test_idx]

            try:
                # Fit model
                model_copy = self._clone_model(model)
                model_copy.fit(X_train, y_train)

                # Predictions
                y_pred = model_copy.predict(X_test)

                # Probabilities for AUC
                if hasattr(model_copy, 'predict_proba'):
                    y_prob = model_copy.predict_proba(X_test)[:, 1]
                elif hasattr(model_copy, 'decision_function'):
                    y_prob = model_copy.decision_function(X_test)
                else:
                    y_prob = y_pred

                # Calculate metrics
                metrics['accuracy'].append(accuracy_score(y_test, y_pred))
                metrics['f1'].append(f1_score(y_test, y_pred, zero_division=0))
                metrics['precision'].append(precision_score(y_test, y_pred, zero_division=0))
                metrics['recall'].append(recall_score(y_test, y_pred, zero_division=0))

                try:
                    metrics['auc'].append(roc_auc_score(y_test, y_prob))
                except:
                    metrics['auc'].append(np.nan)

            except Exception as e:
                logger.warning(f"Fold {fold} failed for {model_name}: {e}")
                for key in metrics:
                    metrics[key].append(np.nan)

        # Aggregate results
        results = {
            'model_name': model_name,
            'cv_type': f'{self.config.n_folds}-fold'
        }
        for key in metrics:
            results[f'{key}_mean'] = np.nanmean(metrics[key])
            results[f'{key}_std'] = np.nanstd(metrics[key])

        return results

    def loo_classification(self, X: np.ndarray, y: np.ndarray,
                          model: Any, model_name: str) -> Dict:
        """Run Leave-One-Out CV for classification."""
        loo = LeaveOneOut()

        y_true = []
        y_pred = []
        y_prob = []

        for train_idx, test_idx in loo.split(X):
            X_train, X_test = X[train_idx], X[test_idx]
            y_train, y_test = y[train_idx], y[test_idx]

            try:
                model_copy = self._clone_model(model)
                model_copy.fit(X_train, y_train)

                pred = model_copy.predict(X_test)[0]
                y_true.append(y_test[0])
                y_pred.append(pred)

                if hasattr(model_copy, 'predict_proba'):
                    prob = model_copy.predict_proba(X_test)[0, 1]
                elif hasattr(model_copy, 'decision_function'):
                    prob = model_copy.decision_function(X_test)[0]
                else:
                    prob = pred
                y_prob.append(prob)

            except Exception as e:
                y_true.append(y_test[0])
                y_pred.append(np.nan)
                y_prob.append(np.nan)

        y_true = np.array(y_true)
        y_pred = np.array(y_pred)
        y_prob = np.array(y_prob)

        # Remove NaN entries
        valid_mask = ~np.isnan(y_pred)
        y_true_valid = y_true[valid_mask]
        y_pred_valid = y_pred[valid_mask]
        y_prob_valid = y_prob[valid_mask]

        results = {
            'model_name': model_name,
            'cv_type': 'LOO',
            'accuracy': accuracy_score(y_true_valid, y_pred_valid) if len(y_true_valid) > 0 else np.nan,
            'f1': f1_score(y_true_valid, y_pred_valid, zero_division=0) if len(y_true_valid) > 0 else np.nan,
            'precision': precision_score(y_true_valid, y_pred_valid, zero_division=0) if len(y_true_valid) > 0 else np.nan,
            'recall': recall_score(y_true_valid, y_pred_valid, zero_division=0) if len(y_true_valid) > 0 else np.nan,
        }

        try:
            results['auc'] = roc_auc_score(y_true_valid, y_prob_valid)
        except:
            results['auc'] = np.nan

        return results

    def stratified_kfold_survival(self, X: np.ndarray, y: np.ndarray,
                                  model: Any, model_name: str) -> Dict:
        """Run stratified 5-fold CV for survival analysis."""
        # y is structured array with (event, time)
        events = y['event']

        skf = StratifiedKFold(n_splits=self.config.n_folds, shuffle=True,
                             random_state=self.config.random_state)

        c_indices = []

        for fold, (train_idx, test_idx) in enumerate(skf.split(X, events)):
            X_train, X_test = X[train_idx], X[test_idx]
            y_train, y_test = y[train_idx], y[test_idx]

            try:
                if isinstance(model, str) and model.startswith('lifelines_'):
                    c_index = self._fit_lifelines_model(model, X_train, y_train, X_test, y_test)
                else:
                    model_copy = self._clone_model(model)
                    model_copy.fit(X_train, y_train)

                    # Get risk scores
                    if hasattr(model_copy, 'predict'):
                        risk_scores = model_copy.predict(X_test)
                    else:
                        risk_scores = model_copy.decision_function(X_test)

                    # Calculate C-index
                    c_index = concordance_index_censored(
                        y_test['event'], y_test['time'], risk_scores
                    )[0]

                c_indices.append(c_index)

            except Exception as e:
                logger.warning(f"Fold {fold} failed for {model_name}: {e}")
                c_indices.append(np.nan)

        results = {
            'model_name': model_name,
            'cv_type': f'{self.config.n_folds}-fold',
            'c_index_mean': np.nanmean(c_indices),
            'c_index_std': np.nanstd(c_indices)
        }

        return results

    def _fit_lifelines_model(self, model_type: str, X_train: np.ndarray, y_train: np.ndarray,
                            X_test: np.ndarray, y_test: np.ndarray) -> float:
        """Fit lifelines survival model and return C-index."""
        # Create DataFrame for lifelines
        train_df = pd.DataFrame(X_train, columns=[f'feature_{i}' for i in range(X_train.shape[1])])
        train_df['time'] = y_train['time']
        train_df['event'] = y_train['event']

        test_df = pd.DataFrame(X_test, columns=[f'feature_{i}' for i in range(X_test.shape[1])])
        test_df['time'] = y_test['time']
        test_df['event'] = y_test['event']

        feature_cols = [f'feature_{i}' for i in range(X_train.shape[1])]

        if model_type == 'lifelines_cox':
            fitter = CoxPHFitter(penalizer=0.1)
            fitter.fit(train_df, duration_col='time', event_col='event')
            partial_hazard = fitter.predict_partial_hazard(test_df)
            risk_scores = partial_hazard.values.flatten()
        elif model_type == 'lifelines_weibull':
            fitter = WeibullAFTFitter(penalizer=0.1)
            fitter.fit(train_df, duration_col='time', event_col='event')
            # For AFT, lower predicted time = higher risk
            risk_scores = -fitter.predict_expectation(test_df).values.flatten()
        elif model_type == 'lifelines_lognormal':
            fitter = LogNormalAFTFitter(penalizer=0.1)
            fitter.fit(train_df, duration_col='time', event_col='event')
            risk_scores = -fitter.predict_expectation(test_df).values.flatten()
        elif model_type == 'lifelines_loglogistic':
            fitter = LogLogisticAFTFitter(penalizer=0.1)
            fitter.fit(train_df, duration_col='time', event_col='event')
            risk_scores = -fitter.predict_expectation(test_df).values.flatten()
        else:
            raise ValueError(f"Unknown lifelines model: {model_type}")

        c_index = concordance_index_censored(
            y_test['event'], y_test['time'], risk_scores
        )[0]

        return c_index

    def _clone_model(self, model: Any) -> Any:
        """Clone a sklearn-style model."""
        from sklearn.base import clone
        try:
            return clone(model)
        except:
            # For models that don't support clone, create new instance
            return model.__class__(**model.get_params())


# =============================================================================
# 8. STATISTICAL TESTING WITH FDR
# =============================================================================

class StatisticalTesting:
    """Statistical testing with FDR correction."""

    def __init__(self, config: Config):
        self.config = config

    def apply_fdr_correction(self, pvalues: np.ndarray,
                            method: str = 'fdr_bh') -> Tuple[np.ndarray, np.ndarray]:
        """Apply Benjamini-Hochberg FDR correction."""
        # Remove NaN values for correction
        valid_mask = ~np.isnan(pvalues)
        valid_pvals = pvalues[valid_mask]

        if len(valid_pvals) == 0:
            return pvalues, np.ones_like(pvalues, dtype=bool)

        # Apply correction
        rejected, corrected_pvals, _, _ = multipletests(
            valid_pvals, alpha=self.config.fdr_alpha, method=method
        )

        # Put back into original array
        corrected_full = np.full_like(pvalues, np.nan)
        rejected_full = np.zeros_like(pvalues, dtype=bool)

        corrected_full[valid_mask] = corrected_pvals
        rejected_full[valid_mask] = rejected

        return corrected_full, rejected_full

    def compile_statistical_results(self, clustering_results: Dict) -> pd.DataFrame:
        """Compile all statistical test results and apply FDR correction."""
        results = []

        for method_name, method_results in clustering_results.items():
            # Chi-square tests
            for cluster_type in ['kmeans', 'hierarchical']:
                stat_key = f'{cluster_type}_chi2_stat'
                pval_key = f'{cluster_type}_chi2_pval'

                if stat_key in method_results and pval_key in method_results:
                    results.append({
                        'aggregation_method': method_name,
                        'clustering_method': cluster_type,
                        'test_type': 'chi_square',
                        'test_statistic': method_results[stat_key],
                        'p_value': method_results[pval_key]
                    })

                # Log-rank tests
                stat_key = f'{cluster_type}_logrank_stat'
                pval_key = f'{cluster_type}_logrank_pval'

                if stat_key in method_results and pval_key in method_results:
                    results.append({
                        'aggregation_method': method_name,
                        'clustering_method': cluster_type,
                        'test_type': 'log_rank',
                        'test_statistic': method_results[stat_key],
                        'p_value': method_results[pval_key]
                    })

        if len(results) == 0:
            return pd.DataFrame()

        df = pd.DataFrame(results)

        # Apply FDR correction separately for each test type
        for test_type in df['test_type'].unique():
            mask = df['test_type'] == test_type
            pvals = df.loc[mask, 'p_value'].values
            corrected, rejected = self.apply_fdr_correction(pvals)
            df.loc[mask, 'p_value_fdr'] = corrected
            df.loc[mask, 'significant_fdr'] = rejected

        return df


# =============================================================================
# 9. RESULTS EXPORT & VISUALIZATION
# =============================================================================

class ResultsExporter:
    """Export results and create visualizations."""

    def __init__(self, config: Config):
        self.config = config

    def save_aggregated_embeddings(self, embeddings_dict: Dict[str, np.ndarray],
                                   slide_ids: List[str]):
        """Save aggregated embeddings to CSV files."""
        output_dir = self.config.output_dir / "aggregated_embeddings"

        for method_name, embeddings in embeddings_dict.items():
            df = pd.DataFrame(embeddings)
            df.index = slide_ids
            df.to_csv(output_dir / f"{method_name}.csv")

        logger.info(f"Saved {len(embeddings_dict)} aggregated embedding files")

    def save_classification_results(self, results: List[Dict]):
        """Save classification results."""
        df = pd.DataFrame(results)
        output_path = self.config.output_dir / "classification_results" / "all_results.csv"
        df.to_csv(output_path, index=False)
        logger.info(f"Saved classification results to {output_path}")
        return df

    def save_survival_results(self, results: List[Dict]):
        """Save survival results."""
        df = pd.DataFrame(results)
        output_path = self.config.output_dir / "survival_results" / "all_results.csv"
        df.to_csv(output_path, index=False)
        logger.info(f"Saved survival results to {output_path}")
        return df

    def save_clustering_results(self, results: Dict):
        """Save clustering results."""
        # Convert to serializable format
        serializable = {}
        for method_name, method_results in results.items():
            serializable[method_name] = {}
            for key, value in method_results.items():
                if isinstance(value, np.ndarray):
                    serializable[method_name][key] = value.tolist()
                elif isinstance(value, (np.integer,)):
                    serializable[method_name][key] = int(value)
                elif isinstance(value, (np.floating,)):
                    serializable[method_name][key] = float(value)
                elif isinstance(value, dict):
                    # Recursively convert nested dicts
                    cleaned = {}
                    for k2, v2 in value.items():
                        if isinstance(v2, np.ndarray):
                            cleaned[k2] = v2.tolist()
                        elif isinstance(v2, (np.integer,)):
                            cleaned[k2] = int(v2)
                        elif isinstance(v2, (np.floating,)):
                            cleaned[k2] = float(v2)
                        else:
                            cleaned[k2] = v2
                    serializable[method_name][key] = cleaned
                else:
                    serializable[method_name][key] = value

        output_path = self.config.output_dir / "clustering_results" / "all_results.json"
        with open(output_path, 'w') as f:
            json.dump(serializable, f, indent=2)

        logger.info(f"Saved clustering results to {output_path}")

    def save_statistical_tests(self, df: pd.DataFrame):
        """Save statistical test results."""
        output_path = self.config.output_dir / "statistical_tests" / "fdr_corrected_results.csv"
        df.to_csv(output_path, index=False)
        logger.info(f"Saved statistical tests to {output_path}")

    def create_summary_report(self, classification_results: pd.DataFrame,
                             survival_results: pd.DataFrame,
                             clustering_results: Dict,
                             statistical_results: pd.DataFrame) -> pd.DataFrame:
        """Create master summary report."""
        summary_rows = []

        aggregation_methods = list(clustering_results.keys())

        for method in aggregation_methods:
            row = {'aggregation_method': method}

            # PCA info
            if method in clustering_results:
                row['pca_n_components'] = clustering_results[method].get('pca_n_components', np.nan)
                row['pca_variance_explained'] = clustering_results[method].get('pca_variance_explained', np.nan)
                row['optimal_k'] = clustering_results[method].get('optimal_k', np.nan)
                row['kmeans_silhouette'] = clustering_results[method].get('kmeans_silhouette', np.nan)
                row['hierarchical_silhouette'] = clustering_results[method].get('hierarchical_silhouette', np.nan)

            # Best classification model
            if len(classification_results) > 0:
                method_class = classification_results[classification_results['aggregation_method'] == method]
                if len(method_class) > 0:
                    best_class = method_class.loc[method_class['auc_mean'].idxmax()] if 'auc_mean' in method_class.columns else None
                    if best_class is not None:
                        row['best_classification_model'] = best_class.get('model_name', '')
                        row['best_classification_auc'] = best_class.get('auc_mean', np.nan)

            # Best survival model
            if len(survival_results) > 0:
                method_surv = survival_results[survival_results['aggregation_method'] == method]
                if len(method_surv) > 0:
                    best_surv = method_surv.loc[method_surv['c_index_mean'].idxmax()] if 'c_index_mean' in method_surv.columns else None
                    if best_surv is not None:
                        row['best_survival_model'] = best_surv.get('model_name', '')
                        row['best_survival_c_index'] = best_surv.get('c_index_mean', np.nan)

            # Statistical significance
            if len(statistical_results) > 0:
                method_stats = statistical_results[statistical_results['aggregation_method'] == method]
                row['n_significant_tests'] = method_stats['significant_fdr'].sum() if 'significant_fdr' in method_stats.columns else 0

            summary_rows.append(row)

        summary_df = pd.DataFrame(summary_rows)
        output_path = self.config.output_dir / "summary_report.csv"
        summary_df.to_csv(output_path, index=False)
        logger.info(f"Saved summary report to {output_path}")

        return summary_df

    def plot_pca_variance(self, pca_results: Dict):
        """Plot PCA variance explained for all methods."""
        fig, ax = plt.subplots(figsize=(12, 6))

        methods = list(pca_results.keys())
        variances = [pca_results[m]['explained_variance'] for m in methods]
        n_components = [pca_results[m]['n_components'] for m in methods]

        x = np.arange(len(methods))
        width = 0.35

        bars1 = ax.bar(x - width/2, variances, width, label='Variance Explained', color='steelblue')

        ax2 = ax.twinx()
        bars2 = ax2.bar(x + width/2, n_components, width, label='N Components', color='coral')

        ax.set_xlabel('Aggregation Method')
        ax.set_ylabel('Variance Explained', color='steelblue')
        ax2.set_ylabel('N Components', color='coral')
        ax.set_xticks(x)
        ax.set_xticklabels(methods, rotation=45, ha='right')
        ax.set_ylim(0.9, 1.0)

        plt.title('PCA Results by Aggregation Method')
        plt.tight_layout()
        plt.savefig(self.config.output_dir / "figures" / "pca_variance.png", dpi=150)
        plt.close()

    def plot_classification_heatmap(self, results: pd.DataFrame):
        """Plot heatmap of classification AUC scores."""
        if len(results) == 0:
            return

        pivot = results.pivot_table(
            values='auc_mean',
            index='aggregation_method',
            columns='model_name',
            aggfunc='mean'
        )

        fig, ax = plt.subplots(figsize=(16, 12))
        sns.heatmap(pivot, annot=True, fmt='.3f', cmap='RdYlGn', ax=ax,
                   vmin=0.5, vmax=1.0, center=0.75)
        plt.title('Classification AUC by Aggregation Method and Model')
        plt.tight_layout()
        plt.savefig(self.config.output_dir / "figures" / "classification_heatmap.png", dpi=150)
        plt.close()

    def plot_survival_heatmap(self, results: pd.DataFrame):
        """Plot heatmap of survival C-index scores."""
        if len(results) == 0:
            return

        pivot = results.pivot_table(
            values='c_index_mean',
            index='aggregation_method',
            columns='model_name',
            aggfunc='mean'
        )

        fig, ax = plt.subplots(figsize=(14, 12))
        sns.heatmap(pivot, annot=True, fmt='.3f', cmap='RdYlGn', ax=ax,
                   vmin=0.4, vmax=0.8, center=0.6)
        plt.title('Survival C-Index by Aggregation Method and Model')
        plt.tight_layout()
        plt.savefig(self.config.output_dir / "figures" / "survival_heatmap.png", dpi=150)
        plt.close()


# =============================================================================
# 10. MAIN EXECUTION PIPELINE
# =============================================================================

class WSIAnalysisPipeline:
    """Main pipeline orchestrating the entire analysis."""

    def __init__(self, config: Optional[Config] = None):
        self.config = config or Config()
        self.data_loader = DataLoader(self.config)
        self.clustering = ClusteringPipeline(self.config)
        self.cv = CrossValidation(self.config)
        self.stats = StatisticalTesting(self.config)
        self.exporter = ResultsExporter(self.config)

        self.aggregation_methods = get_all_aggregation_methods()
        self.survival_models = get_survival_models(self.config.random_state)
        self.classification_models = get_classification_models(self.config.random_state)

    def run(self):
        """Execute the full analysis pipeline."""
        start_time = datetime.now()
        logger.info("=" * 60)
        logger.info("WSI Embedding Analysis Pipeline")
        logger.info(f"Started at: {start_time}")
        logger.info("=" * 60)

        # Step 1: Load data
        logger.info("\n[Step 1/6] Loading data...")
        slides = self.data_loader.discover_slides()

        if len(slides) == 0:
            logger.error("No slides found. Please check the embeddings directory.")
            logger.info(f"Expected location: {self.config.embeddings_dir}")
            self._create_demo_results()
            return

        clinical_data = self.data_loader.load_clinical_data()
        survival_data = self.data_loader.get_survival_data()

        # Step 2: Aggregate embeddings
        logger.info("\n[Step 2/6] Aggregating embeddings...")
        aggregated_embeddings = self._aggregate_all_slides(slides)

        # Get labels
        slide_df = self.data_loader.slide_metadata
        labels = slide_df['is_tumor'].astype(int).values
        slide_ids = slide_df['filename'].tolist()

        # Save aggregated embeddings
        self.exporter.save_aggregated_embeddings(aggregated_embeddings, slide_ids)

        # Step 3: Clustering analysis
        logger.info("\n[Step 3/6] Running clustering analysis...")
        clustering_results = {}
        slide_participant_ids = slide_df['participant_id'].tolist()
        for method_name, embeddings in aggregated_embeddings.items():
            logger.info(f"  Processing {method_name}...")
            results = self.clustering.run_clustering_analysis(
                embeddings, method_name, labels,
                survival_data if len(survival_data) > 0 else None,
                slide_participant_ids=slide_participant_ids
            )
            clustering_results[method_name] = results

        self.exporter.save_clustering_results(clustering_results)

        # Step 4: Classification analysis
        logger.info("\n[Step 4/6] Running classification analysis...")
        classification_results = self._run_classification_analysis(aggregated_embeddings, labels)
        class_df = self.exporter.save_classification_results(classification_results)

        # Step 5: Survival analysis
        logger.info("\n[Step 5/6] Running survival analysis...")
        if len(survival_data) > 0:
            survival_results = self._run_survival_analysis(aggregated_embeddings, survival_data, slide_df)
            surv_df = self.exporter.save_survival_results(survival_results)
        else:
            logger.warning("No survival data available. Skipping survival analysis.")
            surv_df = pd.DataFrame()

        # Step 6: Statistical testing and summary
        logger.info("\n[Step 6/6] Compiling results and statistical tests...")
        stat_df = self.stats.compile_statistical_results(clustering_results)
        self.exporter.save_statistical_tests(stat_df)

        # Create visualizations
        if self.clustering.pca_models:
            self.exporter.plot_pca_variance(self.clustering.pca_models)
        if len(class_df) > 0:
            self.exporter.plot_classification_heatmap(class_df)
        if len(surv_df) > 0:
            self.exporter.plot_survival_heatmap(surv_df)

        # Create summary report
        summary = self.exporter.create_summary_report(
            class_df, surv_df, clustering_results, stat_df
        )

        # Final summary
        end_time = datetime.now()
        duration = end_time - start_time

        logger.info("\n" + "=" * 60)
        logger.info("ANALYSIS COMPLETE")
        logger.info("=" * 60)
        logger.info(f"Duration: {duration}")
        logger.info(f"Results saved to: {self.config.output_dir}")
        logger.info(f"\nSummary:")
        logger.info(f"  - Aggregation methods: {len(self.aggregation_methods)}")
        logger.info(f"  - Classification models: {len(self.classification_models)}")
        logger.info(f"  - Survival models: {len(self.survival_models)}")
        logger.info(f"  - Total classification evaluations: {len(classification_results)}")
        logger.info(f"  - Total survival evaluations: {len(survival_results) if 'survival_results' in dir() else 0}")

        if len(stat_df) > 0:
            n_significant = stat_df['significant_fdr'].sum() if 'significant_fdr' in stat_df.columns else 0
            logger.info(f"  - Significant tests (FDR < 0.05): {n_significant}/{len(stat_df)}")

        return summary

    def _aggregate_all_slides(self, slides: List[Dict]) -> Dict[str, np.ndarray]:
        """Aggregate embeddings for all slides using all methods.

        Processes one file at a time with immediate memory cleanup and
        cooldown pauses between files to stay thermally friendly.
        """
        aggregated = {method: [] for method in self.aggregation_methods}
        total = len(slides)

        for idx, slide_info in enumerate(slides):
            slide_path = slide_info['path']
            logger.info(f"  [{idx + 1}/{total}] Processing {slide_path.name}")

            try:
                # Load embeddings for this single slide
                embeddings = self.data_loader.load_slide_embeddings(slide_path)

                # Apply all aggregation methods
                for method_name, method_func in self.aggregation_methods.items():
                    try:
                        agg_emb = method_func(embeddings)
                        aggregated[method_name].append(agg_emb)
                    except Exception as e:
                        logger.warning(f"Aggregation {method_name} failed for {slide_path.name}: {e}")
                        expected_dim = self._get_expected_dim(method_name)
                        aggregated[method_name].append(np.zeros(expected_dim))

            except Exception as e:
                logger.error(f"Failed to load {slide_path}: {e}")
                for method_name in self.aggregation_methods:
                    expected_dim = self._get_expected_dim(method_name)
                    aggregated[method_name].append(np.zeros(expected_dim))

            # --- Immediate memory cleanup after each file ---
            # Delete the raw embeddings so RAM is freed before the next file
            try:
                del embeddings
            except UnboundLocalError:
                pass
            gc.collect()

            # --- Cooldown pause between files ---
            if idx < total - 1:
                time.sleep(self.config.cooldown_seconds)

        # Convert to arrays
        for method_name in aggregated:
            aggregated[method_name] = np.array(aggregated[method_name])
            logger.info(f"  {method_name}: {aggregated[method_name].shape}")

        return aggregated

    def _get_expected_dim(self, method_name: str) -> int:
        """Get expected output dimension for an aggregation method."""
        mega_dims = {
            'mega_mean_minmax': 4608,
            'mega_mean_extremes': 7680,
            'mega_mean_percentiles': 7680,
            'mega_central_spread': 7680,
            'mega_robust': 7680,
            'mega_full': 10752,
            'mega_distribution': 6144,
            'mega_all_percentiles': 10752,
        }
        return mega_dims.get(method_name, self.config.embedding_dim)

    def _run_classification_analysis(self, aggregated_embeddings: Dict[str, np.ndarray],
                                     labels: np.ndarray) -> List[Dict]:
        """Run classification analysis for all aggregation methods and models."""
        results = []

        total_combos = len(aggregated_embeddings) * len(self.classification_models)
        current = 0

        for method_name, embeddings in aggregated_embeddings.items():
            # PCA first
            embeddings_pca, _ = self.clustering.fit_pca(embeddings, f"class_{method_name}")

            for model_name, model in self.classification_models.items():
                current += 1
                logger.info(f"  [{current}/{total_combos}] {method_name} + {model_name}")

                try:
                    # 5-fold CV
                    cv_result = self.cv.stratified_kfold_classification(
                        embeddings_pca, labels, model, model_name
                    )
                    cv_result['aggregation_method'] = method_name
                    results.append(cv_result)

                except Exception as e:
                    logger.warning(f"Classification failed for {method_name} + {model_name}: {e}")
                    results.append({
                        'aggregation_method': method_name,
                        'model_name': model_name,
                        'cv_type': f'{self.config.n_folds}-fold',
                        'auc_mean': np.nan,
                        'auc_std': np.nan,
                        'f1_mean': np.nan,
                        'f1_std': np.nan,
                        'accuracy_mean': np.nan,
                        'accuracy_std': np.nan,
                        'error': str(e)
                    })

        return results

    def _run_survival_analysis(self, aggregated_embeddings: Dict[str, np.ndarray],
                               survival_data: pd.DataFrame,
                               slide_df: pd.DataFrame) -> List[Dict]:
        """Run survival analysis for all aggregation methods and models."""
        results = []

        # Match survival data with slide embeddings
        # Create participant to index mapping
        participant_to_idx = {}
        for idx, row in slide_df.iterrows():
            participant_to_idx[row['participant_id']] = idx

        # Find common samples
        common_participants = set(survival_data['participant_id']).intersection(
            set(slide_df['participant_id'])
        )

        if len(common_participants) == 0:
            logger.warning("No matching samples between embeddings and survival data")
            return results

        logger.info(f"Found {len(common_participants)} samples with both embeddings and survival data")

        # Create aligned indices
        survival_indices = []
        embedding_indices = []

        for participant in common_participants:
            surv_idx = survival_data[survival_data['participant_id'] == participant].index[0]
            emb_idx = slide_df[slide_df['participant_id'] == participant].index[0]
            survival_indices.append(surv_idx)
            embedding_indices.append(emb_idx)

        # Create structured array for survival
        aligned_survival = survival_data.loc[survival_indices]
        y = np.array(
            [(bool(row['event']), row['time']) for _, row in aligned_survival.iterrows()],
            dtype=[('event', bool), ('time', float)]
        )

        total_combos = len(aggregated_embeddings) * len(self.survival_models)
        current = 0

        for method_name, embeddings in aggregated_embeddings.items():
            # Get aligned embeddings
            X = embeddings[embedding_indices]

            # PCA
            embeddings_pca, _ = self.clustering.fit_pca(X, f"surv_{method_name}")

            for model_name, model in self.survival_models.items():
                current += 1
                logger.info(f"  [{current}/{total_combos}] {method_name} + {model_name}")

                try:
                    cv_result = self.cv.stratified_kfold_survival(
                        embeddings_pca, y, model, model_name
                    )
                    cv_result['aggregation_method'] = method_name
                    results.append(cv_result)

                except Exception as e:
                    logger.warning(f"Survival failed for {method_name} + {model_name}: {e}")
                    results.append({
                        'aggregation_method': method_name,
                        'model_name': model_name,
                        'cv_type': f'{self.config.n_folds}-fold',
                        'c_index_mean': np.nan,
                        'c_index_std': np.nan,
                        'error': str(e)
                    })

        return results

    def _create_demo_results(self):
        """Create demo results when no real data is available."""
        logger.info("\nCreating demo results structure...")

        # Create empty summary
        summary = {
            'status': 'no_data',
            'message': 'No embedding files found. Pipeline structure verified.',
            'expected_location': str(self.config.embeddings_dir),
            'aggregation_methods': list(self.aggregation_methods.keys()),
            'classification_models': list(self.classification_models.keys()),
            'survival_models': list(self.survival_models.keys())
        }

        with open(self.config.output_dir / "demo_summary.json", 'w') as f:
            json.dump(summary, f, indent=2)

        logger.info(f"Demo summary saved to {self.config.output_dir / 'demo_summary.json'}")


def main():
    """Main entry point."""
    import argparse

    parser = argparse.ArgumentParser(description='WSI Embedding Analysis Pipeline')
    parser.add_argument('--embeddings-dir', type=str,
                       default=r'C:\Users\Jia Yin\Desktop\Mentorship\JiaYin_WSI_Analysis\embeddings',
                       help='Directory containing H5 embedding files')
    parser.add_argument('--clinical-data', type=str,
                       default=r'C:\Users\Jia Yin\Desktop\Mentorship\JiaYin_WSI_Analysis\CLINICAL_FULL.parquet',
                       help='Path to clinical data parquet file')
    parser.add_argument('--output-dir', type=str,
                       default=r'C:\Users\Jia Yin\Desktop\Mentorship\JiaYin_WSI_Analysis\results',
                       help='Output directory for results')
    parser.add_argument('--cancer-type', type=str, default='CHOL',
                       help='TCGA cancer type code')
    parser.add_argument('--n-folds', type=int, default=5,
                       help='Number of CV folds')
    parser.add_argument('--random-state', type=int, default=42,
                       help='Random seed')
    parser.add_argument('--cooldown', type=float, default=0.5,
                       help='Seconds to pause between files (thermal management)')

    args = parser.parse_args()

    # Create config
    config = Config(
        embeddings_dir=Path(args.embeddings_dir),
        clinical_data_path=Path(args.clinical_data),
        output_dir=Path(args.output_dir),
        cancer_type=args.cancer_type,
        n_folds=args.n_folds,
        random_state=args.random_state,
        cooldown_seconds=args.cooldown
    )

    # Run pipeline
    pipeline = WSIAnalysisPipeline(config)
    pipeline.run()


if __name__ == '__main__':
    main()
